import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white">
        <header className="bg-white border-b sticky top-0 z-10">
          <nav className="max-w-6xl mx-auto px-4 h-16 flex items-center justify-between">
            <Link href="/" className="font-bold text-xl text-blue-600">Demo App</Link>
            <ul className="flex gap-6">
              <li>
                <Link href="/messages" className="text-gray-600 hover:text-blue-600 font-medium transition-colors">
                  メッセージ投稿
                </Link>
              </li>
              <li>
                <Link href="/sql-console" className="text-gray-600 hover:text-blue-600 font-medium transition-colors">
                  SQLエディタ
                </Link>
              </li>
              <li>
                <Link href="/python-editor" className="text-gray-600 hover:text-green-600 font-medium transition-colors">
                  Pythonエディタ
                </Link>
              </li>
              <li>
                <Link href="/spring-book" className="text-gray-600 hover:text-blue-600 font-medium transition-colors">
                  Spring-Bookエディタ
                </Link>
              </li>
              <li>
                <Link href="/screen-to-md" className="text-gray-600 hover:text-purple-600 font-medium transition-colors">
                  Screen to MD
                </Link>
              </li>
              <li>
                <Link href="/wooldridge" className="text-gray-600 hover:text-orange-600 font-medium transition-colors">
                  Wooldridge
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
